spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: skillbox
    password: skillbox

  #  liquibase:
  #    enabled: true
  #    drop-first: false
  #    change-log: classpath:db/db-changelog-master.xml
  #    default-schema: public

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public
